### ISSUE TITLE
Error received after updating to 6.5.0

### ISSUE THREAD

**Issue by mcrawshaw** [birdofpreyru/babel-plugin-react-css-modules#21]
Not sure why, but when switching from 6.4.1 to 6.5.0, my compile fails with:
```
ERROR in ./src/universal/ui/widgets/form/FormRatingUiw.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: localident.replace(...).replace(...).replace(...).replaceAll is not a function
    at /Users/markcrawshaw/Code/metamap/src/universal/ui/widgets/form/FormRatingUiw.pcss:1:1
    at escapeLocalIdent (/Users/markcrawshaw/Code/metamap/node_modules/@dr.pogodin/babel-plugin-react-css-modules/dist/getLocalIdent.js:197:101)
    at getLocalIdent (/Users/markcrawshaw/Code/metamap/node_modules/@dr.pogodin/babel-plugin-react-css-modules/dist/getLocalIdent.js:297:10)
    at generateScopedName (/Users/markcrawshaw/Code/metamap/node_modules/@dr.pogodin/babel-plugin-react-css-modules/dist/requireCssModule.js:95:41)
    at exportScopedName (/Users/markcrawshaw/Code/metamap/node_modules/postcss-modules-scope/src/index.js:95:28)
    at localizeNode (/Users/markcrawshaw/Code/metamap/node_modules/postcss-modules-scope/src/index.js:124:22)
    at Array.map (<anonymous>)
    at Selector.map (/Users/markcrawshaw/Code/metamap/node_modules/postcss-selector-parser/dist/selectors/container.js:347:23)
    at localizeNode (/Users/markcrawshaw/Code/metamap/node_modules/postcss-modules-scope/src/index.js:120:31)
    at traverseNode (/Users/markcrawshaw/Code/metamap/node_modules/postcss-modules-scope/src/index.js:152:32)
    at Selector.each (/Users/markcrawshaw/Code/metamap/node_modules/postcss-selector-parser/dist/selectors/container.js:207:16)
```

**Comment by birdofpreyru** [comment]
Thanks for reporting @mcrawshaw , and sorry about it. The updated ESLint config insisted to replace `.replace(/\./g, '-')` call at that place by `.replaceAll('.', '-')`. And so I did without realizing that `.replaceAll()` is supported by node only since v15.0.0, and I guess yours, and many other projects, still rely on previous node versions. I'll revert that change shortly.

**Comment by birdofpreyru** [comment]
v6.5.1 released, should fix the problem.

**Comment by mcrawshaw** [comment]
Thanks @birdofpreyru , can confirm now working.
